name: apiverve_colorsimilarity
description: Color Similarity Calculator is a tool for calculating similarity between two colors. It uses multiple algorithms including RGB distance, HSL comparison, and Delta E to provide comprehensive color similarity analysis.
version: 1.1.14
homepage: https://apiverve.com/marketplace/colorsimilarity?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/colorsimilarity-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
